require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'SQL_PlayGround' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'SQL_PlayGroundTests' do
    pod 'Google-Mobile-Ads-SDK'
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'SQL_PlayGround-tvOS' do
  # Pods for SQL_PlayGround-tvOS

  target 'SQL_PlayGround-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
