# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new build to Appstore"
  lane :deploy do
    sync_code_signing(type: "appstore")
    
    build_app(workspace: "SQL_PlayGround.xcworkspace", scheme: "SQL_PlayGround")
    
    changelog_from_git_commits 
    
    upload_to_app_store(
      submit_for_review: true,
      automatic_release: true,
      force: true, # Skip HTMl report verification
      skip_metadata: true,
      skip_screenshots: true,
    )
  end

  desc "Upload to testflight"
  lane :beta do
    app_store_connect_api_key(
      key_id: "MAWV922B64",
      issuer_id: "64750f88-f163-4a44-990c-c3e5baff9932",
      key_filepath: "./authkey.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    sync_code_signing(type: "appstore")
    
    build_app(workspace: "SQL_PlayGround.xcworkspace", scheme: "SQL_PlayGround")
    
    changelog_from_git_commits 

    upload_to_testflight
  end

  desc "Upload to app store"
  lane :upload do
    app_store_connect_api_key(
      key_id: "MAWV922B64",
      issuer_id: "64750f88-f163-4a44-990c-c3e5baff9932",
      key_filepath: "./authkey.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    pilot
    changelog_from_git_commits 
    
    upload_to_app_store(
      submit_for_review: true,
      automatic_release: true,
      force: true, # Skip HTMl report verification
      skip_metadata: true,
      skip_screenshots: true,

      submission_information: {
        add_id_info_limits_tracking: true,
        add_id_info_serves_ads: false,
        add_id_info_tracks_action: true,
        add_id_info_tracks_install: true,
        add_id_info_uses_idfa: true,
        content_rights_has_rights: true,
        content_rights_contains_third_party_content: true,
        export_compliance_platform: 'ios',
        export_compliance_compliance_required: false,
        export_compliance_encryption_updated: false,
        export_compliance_app_type: nil,
        export_compliance_uses_encryption: false,
        export_compliance_is_exempt: false,
        export_compliance_contains_third_party_cryptography: false,
        export_compliance_contains_proprietary_cryptography: false,
        export_compliance_available_on_french_store: false
      }

    )
  end

end


