name: E2E (iOS)

on: [push]

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  build:
    name: E2E (iOS)
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v1

      - name: Setup secret files    
        env: 
          APP_ENV: ${{ secrets.APP_ENV }}
        run: |
          echo $APP_ENV > '.env'

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Get xcode 13
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.5.1'

      - name: Cache Pods
        uses: actions/cache@v1
        id: podcache
        with:
          path: ios/Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Install Pod Dependencies
        run: cd ./ios && pod install && cd ..

      - name: Install Detox Dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Rebuild detox
        # if: steps.cache.outputs.cache-hit == 'true'
        run: yarn detox-setup

      - name: Run Detox Build
        run: yarn e2e:build ios.release

      - name: Run Detox Test(s)
        run: yarn e2e:test ios.release --cleanup

